### ISSUE TITLE
otorrent default url

### ISSUE THREAD

**Issue by kit-ty-kate** [nojb/ocaml-bt#2]
Is this intended ?

https://github.com/nojb/ocaml-bt/blob/a6c8c214e70cd207ad96b8dda5393b1c24180fdc/otorrent/otorrent.ml#L32

**Comment by nojb** [comment]
Thanks for the ping!

FYI, this project is bitrotted and a bit moribund - I am hoping to revisit it in the near future but for now it is in an unusable state.

Anyway, I will remove the explicit URL, as it is not very professional 😄 Thanks!

**Comment by kit-ty-kate** [comment]
No worries, thanks :)
